CXXFLAGS=/Zi $(if $(D),/O0,/O2) -Wall /EHsc /DNOMINMAX
LDFLAGS=/debug
CDEFS?=/DWITH_CATCH
CXX=cl.exe
LD=cl.exe
all: unittests

unittests.exe: unittests.obj unittests2.obj test-asn1.obj
	$(LD) $(LDFLAGS) /Fe:$@  $^

%.obj: %.cpp
	$(CXX) $(CXXFLAGS) $(CDEFS) /c $^ /Fo:$@


clean:
	$(RM) unittests.exe $(wildcard *.obj)

