DOCTEST?=1
CXXFLAGS+=-Zi $(if $(D),/O0,/O2) -Wall -EHsc -DNOMINMAX
CXXFLAGS+=-std:c++17
CXXFLAGS+=-I .
CXXFLAGS+=-utf-8
LDFLAGS=-debug
CDEFS?=$(if $(DOCTEST),-DWITH_DOCTEST,-DWITH_CATCH)
CXX=cl.exe
LD=cl.exe

all: unittests.exe

unittests.exe: $(filter-out test-makeasn1.obj test-fhandle.obj,$(notdir $(subst .cpp,.obj,$(wildcard tests/*.cpp))))
	$(LD) $(LDFLAGS) -Fe:$@  $^

%.obj: tests/%.cpp
	$(CXX) $(CXXFLAGS) $(CDEFS) -c $^ -Fo:$@


clean:
	$(RM) unittests.exe $(wildcard *.obj)

