DOCTEST?=1
CXXFLAGS=/Zi $(if $(D),/O0,/O2) -Wall /EHsc /DNOMINMAX
CXXFLAGS+=/std:c++17
LDFLAGS=/debug
CDEFS?=$(if $(DOCTEST),-DWITH_DOCTEST,-DWITH_CATCH)
CXX=cl.exe
LD=cl.exe

all: unittests.exe

unittests.exe: unittests.obj unittests2.obj
	#	test-asn1.obj
	$(LD) $(LDFLAGS) /Fe:$@  $^

%.obj: %.cpp
	$(CXX) $(CXXFLAGS) $(CDEFS) /c $^ /Fo:$@


clean:
	$(RM) unittests.exe $(wildcard *.obj)

